export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode; // RootLayout은 자식 객체를 받는다
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
